[build]
  command = "sed -i \"s|%%SUPABASE_URL%%|${SUPABASE_URL}|g; s|%%SUPABASE_KEY%%|${SUPABASE_KEY}|g\" js/shared.js"
  publish = "."

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "js/shared.js"

[[redirects]]
  from = "/admin"
  to = "/index.html"
  status = 200
